blog/urls.py
from django.conf.urls import patterns, url
import blog.views

urlpatterns = patterns('blog.views',
                       url(r'^$', blog.views.index, name='index'),
                       )

showcase_project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^showcase/', include('showcase_app.urls', namespace='showcase_app')),
    url(r'^biebfeed/', include('biebfeed.urls', namespace='biebfeed')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^flagship/', include('flagship.urls', namespace='flagship')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^redditclone/', include('redditclone.urls', namespace='redditclone')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>{% block title %}This is the default title.{% endblock %}</title>

    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="{% static 'javascript/jquery.hotkeys.js' %}"></script>
    <script src="{% static 'javascript/sprite.js' %}"></script>

  </head>

  <body>
    <script>
     // makes sure jQuery is working
    if (typeof jQuery == 'undefined') {
      alert("jQuery failed to load");
    }
    </script>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/showcase/">THE SHOWCASE</a>
        </div>

          <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'showcase_app:index' %}">Home</a></li>
                <li><a href="{% url 'showcase_app:projects' %}">Projects</a></li>
                <li><a href="{% url 'blog:index' %}">Blog</a></li>
                <li><a href="{% url 'showcase_app:contact' %}">Contact</a></li>
                {% if user.is_authenticated %}
		        <li><a href="{% url 'showcase_app:profile' pk=user.pk %}">{{ user.username }}</a></li>
                <li><a href="{% url 'auth_logout'%}?next=/showcase/">Logout</a></li>
                {% else %}
                <li><a href="{% url 'registration_register'%}">Register</a></li>
                <li><a href="{% url 'auth_login'%}">Login</a></li>
                {% endif %}
          </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
		{% block side_block %}{% endblock %}
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

          <h1>{% block body_block %}This is the default body_block content.{% endblock %}</h1>


                  {% if user.is_authenticated %}
                    <p>You are logged in as {{ user.username }}</p>
                  {% else %}
                    <p><a href="{% url 'auth_login' %}">Login</a> or <a href="{% url 'registration_register' %}">register</a> for full functionality!</p>
                  {% endif %}
           </div>
        </div>
      </div>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>

  </body>
</html>