biebfeed/urls.py
from django.conf.urls import patterns, url
import biebfeed.views

urlpatterns = patterns('biebfeed.views',
                       url(r'^$', biebfeed.views.index, name="index"),
                       url(r'^friends/$', biebfeed.views.friends, name="friends"),
                       url(r'^delete_friend/', biebfeed.views.delete_friend, name="delete_friend"),
                       url(r'^add_friend/', biebfeed.views.add_friend, name="add_friend")
                       )

blog/urls.py
from django.conf.urls import patterns, url
import blog.views

urlpatterns = patterns('blog.views',
                       url(r'^$', blog.views.index, name='index'),
                       )

showcase_project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^showcase/', include('showcase_app.urls', namespace='showcase_app')),
    url(r'^biebfeed/', include('biebfeed.urls', namespace='biebfeed')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^flagship/', include('flagship.urls', namespace='flagship')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^redditclone/', include('redditclone.urls', namespace='redditclone')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

biebfeed/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class TwitterTarget(models.Model):
    user = models.ForeignKey(User)
    target_username = models.CharField(max_length=20)
    def __str__(self):
        return self.target_username

biebfeed/forms.py
from django import forms
from biebfeed.models import TwitterTarget

class FriendForm(forms.ModelForm):

    class Meta:
        model = TwitterTarget
        fields = ('user', 'target_username',)

biebfeed/views.py
from django.shortcuts import render, HttpResponse
from biebfeed import twitterbot
from biebfeed.models import TwitterTarget


def index(request):
    current_user = request.user
    context_dict = {}
    master_tweet_dict = {}

    if str(current_user) != 'AnonymousUser':

        print("current user is:" + str(current_user))

        twitter_targets = TwitterTarget.objects.filter(user__username__contains=current_user)

        for target in twitter_targets:
            master_tweet_dict[target.target_username] = twitterbot.get_user_tweets(target.target_username)

        context_dict['master_tweet_dict'] = master_tweet_dict

    else:
        master_tweet_dict['justinbieber'] = twitterbot.get_user_tweets('justinbieber')
        context_dict['master_tweet_dict'] = master_tweet_dict

    return render(request, 'biebfeed/index.html', context_dict)

def friends(request):
    current_user = request.user
    context_dict = {}

    friends = TwitterTarget.objects.filter(user__username__contains=current_user)
    friend_list = []

    for friend in friends:
        friend_list.append(friend.target_username)


    context_dict['friend_list'] = friend_list

    return render(request, 'biebfeed/friends.html', context_dict)

def delete_friend(request):
    return HttpResponse('friend removed')

def add_friend(request):
    return HttpResponse('friend added')

templates/biebfeed/friends.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}BIEBFEED - friends{% endblock %}

{% block body_block %}

<h1>These are your friends!</h1>
<ul>
{% for friend in friend_list %}
    <li>{{ friend }} - <a href="{% url 'biebfeed:delete_friend' %}">REMOVE</a></li>
{% endfor %}
</ul>

<form id="add_friend" method="post" action="{% url 'biebfeed:add_friend' %}">

    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}
        {{ field }}
    {% endfor %}

    <input type="submit" name="submit" value="Add Friend">

</form>



{% endblock %}

templates/biebfeed/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}BIEBFEED{% endblock %}

{% block body_block %}
<h1>This is the BIEBFEED.</h1>

{% if user.is_authenticated %}
<h1>You are logged in. Customizable list coming soon!</h1>
<h1><a href="{% url 'biebfeed:friends' %}">FRIENDS</a></h1>
{% else %}
<h1><a href ="{% url 'auth_login'%}">Login</a> to customize your list of friends!</h1>
{% endif %}

{% for key, value, other in master_tweet_dict.items %}
        <h1>{{ key }}</h1>
            <ul>
                <li>{{ value.0 }}</li>
                <li>{{ value.1 }}</li>
                <li>{{ value.2 }}</li>
                <li>{{ value.3 }}</li>
                <li>{{ value.4 }}</li>
            </ul>
{% endfor %}<br>


<h4>
<p>For this simple app, I built a small wrapper for the tweepy python module. It queries
the twitter API and formats the results into a context_dict that is interpreted by a
django template. This is pretty limited at this point, but in the future I hope to add
in authentication functionality and allow users to have personalized lists of twitter
feeds they want to follow. Furthermore, I will need a better way of displaying the
tweets!</p>
</h4>

{% endblock %}