blog/urls.py
from django.conf.urls import patterns, url
import blog.views

urlpatterns = patterns('blog.views',
                       url(r'^$', blog.views.index, name='index'),
                       )

showcase_app/urls.py
from django.conf.urls import patterns, url
from showcase_app import views
from showcase_app.views import UserProfileDetailView, UserProfileEditView
from django.contrib.auth.decorators import login_required as auth
from django.core.urlresolvers import reverse_lazy
from showcase_app.models import UserProfile


urlpatterns = patterns('showcase_app.views',
                       url(r'^$', views.index, name='index'),
                       url(r'^contact/', views.contact, name='contact'),
                       url(r'^projects/', views.projects, name='projects'),
                       url(r'^users/(?P<pk>\w+)/$', UserProfileDetailView.as_view(template_name="showcase_app/user_profile.html"), name="profile"),
                       url(r'^edit_profile/(?P<pk>\w+)/$', auth(UserProfileEditView.as_view(template_name="showcase_app/edit_profile.html", success_url='/showcase/')), name="edit_profile"),
                       )

showcase_project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^showcase/', include('showcase_app.urls', namespace='showcase_app')),
    url(r'^biebfeed/', include('biebfeed.urls', namespace='biebfeed')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^flagship/', include('flagship.urls', namespace='flagship')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^redditclone/', include('redditclone.urls', namespace='redditclone')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

showcase_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    bio = models.TextField(null=True)
    
    def __str__(self):
        return "%s's profile" % self.user

    def get_absolute_url(self):
        return reverse('showcase_app.views.profile', args=[str(self.pk)])

showcase_app/forms.py
from django import forms
from showcase_app.models import UserProfile
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import UpdateView

class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    message = forms.CharField(required=True, widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['contact_name'].label = "Your name:"
        self.fields['contact_email'].label = "Your email:"
        self.fields['message'].label = "Message:"


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ['bio' ]

showcase_app/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.template import Context
from django.template.loader import get_template
from django.core.mail import EmailMessage
from django.contrib.auth import get_user_model
from django.views.generic import DetailView, FormView, UpdateView
from showcase_app.models import UserProfile
from showcase_app.forms import ContactForm, UserProfileForm
from django.core.urlresolvers import reverse

def index(request):
    return render(request, 'showcase_app/index.html', {})

def projects(request):
    return render(request, 'showcase_app/projects.html', {})

def contact(request):
    form_class = ContactForm

    if request.method == 'POST':
        form = form_class(data=request.POST)

        if form.is_valid():
            contact_name = request.POST.get('contact_name', '')
            contact_email = request.POST.get('contact_email', '')
            message = request.POST.get('message', '')

            template = get_template('contact_template.txt')
            context = Context({
                'contact_name': contact_name,
                'contact_email': contact_email,
                'message': message
            })

            content = template.render(context)

            email = EmailMessage(
                'New contact form submission',
                content,
                "Your website",
                ['chrissiegman@yahoo.com'],
                headers = {'Reply-To': contact_email }
            )
            email.send()
            return HttpResponse('Email Sent')
            #return render(request, 'showcase_app/projects.html', {})
            # should this be an HttpResponseRedirect?

        else:
            return HttpResponse('Error: form submission invalid.')
            #return render(request, 'showcase_app/projects.html', {})
    else:
        return render(request, 'showcase_app/contact.html', {'form': form_class})

class UserProfileDetailView(DetailView):
    model = get_user_model()
    slug_field = "username"

    def get_object(self, queryset=None):
        user = super(UserProfileDetailView, self).get_object(queryset)
        UserProfile.objects.get_or_create(user=user)
        return user

class UserProfileEditView(UpdateView):
    model = UserProfile
    fields = ['bio']

templates/showcase_app/contact.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}CONTACT{% endblock %}

{% block body_block%}
    <h1>Contact me!</h1>
    <form action = "" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type ="submit">Submit</button>
    </form>

<h4><p>
    Built this form from scratch. Although it uses the Django email backend, it currently just
    outputs the email to the server terminal.
</p></h4>

{% endblock %}

templates/showcase_app/edit_profile.html
{% extends 'base.html' %}

{% block body_block %}
<h1>{{ user.username }}'s Profile</h2>

<form method="post" action="">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Edit">
</form>

{% endblock %}

templates/showcase_app/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}INDEX{% endblock %}

{% block body_block%}
<h1><p>Welcome to the index page!</p></h1>

<h3><p>
    This project is a showcase of several Django applications I've made.<br>
    You can view the source code <a href="https://github.com/chrissiegman/showcase-project">here</a>.
</p></h3>
{% endblock %}

templates/showcase_app/projects.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}PROJECTS{% endblock %}

{% block body_block%}

<h1><p>This is the projects page.</p></h1>

<h3><ul>

    <li><a href="{% url 'redditclone:index' %}">REDDITCLONE</a> - an app for posting, commenting, and voting on links</li><br>
    <li><a href="{% url 'biebfeed:index' %}">BIEBFEED</a> - a django app that uses tweepy to query Twitter API</li><br>
    <li><a href="{% url 'blog:index' %}">BLOG</a> - a simple blog for keeping track of TO DO items, notes, etc.</li><br>
    <li><a href="{% url 'flagship:index' %}">FLAGSHIP</a> - a JS/JQuery/Canvas game</li><br>
</ul></h3>

<h4><p>
    These projects are all separate django apps that I've wired into the "showcase_app" application.
    Once I implement authentication, they will have bonus features for registered users. The site will
    consist of several pluggable, reusable applications.
</p></h4>
<br>

{% endblock %}

templates/showcase_app/user_profile.html
{% extends 'base.html' %}

{% block body_block %}
<h2>{{ object.username }}'s Profile</h2>
{% if object.userprofile.bio %}
<div>
<b>Bio:</b>
{{ object.userprofile.bio }}
</div>
{% endif %}
{% if object.username == user.username %}
<p><a href='{% url "showcase_app:edit_profile" pk=object.pk %}'>Edit my profile</a></p>
{% endif %}

{% endblock %}